title: "Kishor's Loop of Though"
description: "Where code meets curiosity—tech musings from the trenches of software and AI, exploring the logic behind machines and the mind behind the maker. Not just another tech blog—this one thinks, reflects, and sometimes dreams in code."
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional settings
show_downloads: false
google_analytics:
