title: "Kishor's Blog"
description: "Exploring SQL, finance, and tech insights"
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional settings
show_downloads: true
google_analytics:  # Add your tracking ID here if needed
